theme: minima
include:
  - assets/style.css
  # My-star-wars-journal
Two months, fourteen chapters. Started with Andor. Chrono order, candid takes. Hope, politics, clones, loss, from droids to clones and everything in between.