title: "Two months, fourteen chapters. Started with Andor. Chrono order, candid takes. Hope, politics, clones, loss, from droids to clones and everything in between."
theme: minima
include:
  - assets/style.css
